/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;


import control.FuncionarioBanco;
import javax.swing.JOptionPane;
import modelo.Funcionario;
import control.ValidaCpf;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kaique Spagnol Tofoli
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    private Funcionario func = new Funcionario();
    
    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBorda = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        NomeDeUsuario = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        Senha = new javax.swing.JLabel();
        jPSenha = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Atribuicao = new javax.swing.JLabel();
        jCPadrao = new javax.swing.JCheckBox();
        jCFarmaceutico = new javax.swing.JCheckBox();
        jCGerente = new javax.swing.JCheckBox();
        jCaixa = new javax.swing.JCheckBox();
        jBSalvar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jTCpf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SIFO - Cadastro de Funcionarios");

        jPBorda.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));

        Titulo.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        Titulo.setText("Cadastro de Funcionarios");

        LabelNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelNome.setText("Nome:");

        CPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CPF.setText("CPF:");

        NomeDeUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NomeDeUsuario.setText("Nome de Usuario:");

        Senha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Senha.setText("Senha:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Atribuicao.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Atribuicao.setText("Atribuições");

        jCPadrao.setText("Padrão");
        jCPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPadraoActionPerformed(evt);
            }
        });

        jCFarmaceutico.setText("Farmaceutico");
        jCFarmaceutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFarmaceuticoActionPerformed(evt);
            }
        });

        jCGerente.setText("Gerente");
        jCGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCGerenteActionPerformed(evt);
            }
        });

        jCaixa.setText("Caixa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(Atribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jCPadrao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCFarmaceutico)
                .addGap(38, 38, 38)
                .addComponent(jCGerente)
                .addGap(30, 30, 30)
                .addComponent(jCaixa)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Atribuicao)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCPadrao)
                    .addComponent(jCFarmaceutico)
                    .addComponent(jCGerente)
                    .addComponent(jCaixa))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBordaLayout = new javax.swing.GroupLayout(jPBorda);
        jPBorda.setLayout(jPBordaLayout);
        jPBordaLayout.setHorizontalGroup(
            jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPBordaLayout.createSequentialGroup()
                .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBordaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPBordaLayout.createSequentialGroup()
                        .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBordaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNome)
                                    .addComponent(CPF)
                                    .addComponent(NomeDeUsuario)
                                    .addComponent(Senha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                            .addGroup(jPBordaLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jBSalvar)
                                .addGap(63, 63, 63)
                                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPBordaLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(Titulo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPBordaLayout.setVerticalGroup(
            jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBordaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF)
                    .addComponent(jTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeDeUsuario)
                    .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senha)
                    .addComponent(jPSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalvar)
                    .addComponent(jBSair))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBorda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBorda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPadraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCPadraoActionPerformed

    private void jCFarmaceuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFarmaceuticoActionPerformed
        
        if(jCFarmaceutico.isSelected() == true){
            func.setcrf((JOptionPane.showInputDialog(this,"Digite seu CRF: ","SIFO - Farmaceutico",JOptionPane.NO_OPTION)));
            
        
        }
        
    }//GEN-LAST:event_jCFarmaceuticoActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
               
        func.setNome(jTNome.getText());
        func.setNomeUsuario(jTUsuario.getText());
        func.setSenha(jPSenha.getPassword().toString());
       
        /* VERIFICAÇÃO DE PERMISSÕES */
        
        if(jCGerente.isSelected() == true){
        func.setpermissao("G");   
        }
        else if(jCPadrao.isSelected() == true){
        func.setpermissao("P");   
        }
        
        else if(jCaixa.isSelected() == true){
        func.setpermissao("C");   
        }
        
        /* Validação de CPF */
        
        if (ValidaCpf.isCPF(jTCpf.getText()) == true){
        jTCpf.setText(ValidaCpf.imprimeCPF(jTCpf.getText()));
        func.setCpf(jTCpf.getText());
        }
        else{
        JOptionPane.showMessageDialog(this,"O CPF digitado esta incorreto");
        }
        
        /* SALVAR NO BANCO */
        
        try {
            FuncionarioBanco.getInstance().salvar(func);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jCGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCGerenteActionPerformed
 
    }//GEN-LAST:event_jCGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atribuicao;
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel NomeDeUsuario;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JCheckBox jCFarmaceutico;
    private javax.swing.JCheckBox jCGerente;
    private javax.swing.JCheckBox jCPadrao;
    private javax.swing.JCheckBox jCaixa;
    private javax.swing.JPanel jPBorda;
    private javax.swing.JPasswordField jPSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTCpf;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
